/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVpsRouteImport } from './routes/_authenticated/vps'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAiSettingsRouteImport } from './routes/_authenticated/ai-settings'
import { Route as ApiPublicMetaWebhookRouteImport } from './routes/api/public/meta.webhook'
import { Route as ApiPublicBotWebhookMessageRouteImport } from './routes/api/public/bot.webhook.message'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVpsRoute = AuthenticatedVpsRouteImport.update({
  id: '/vps',
  path: '/vps',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiSettingsRoute = AuthenticatedAiSettingsRouteImport.update({
  id: '/ai-settings',
  path: '/ai-settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicMetaWebhookRoute = ApiPublicMetaWebhookRouteImport.update({
  id: '/api/public/meta/webhook',
  path: '/api/public/meta/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotWebhookMessageRoute =
  ApiPublicBotWebhookMessageRouteImport.update({
    id: '/api/public/bot/webhook/message',
    path: '/api/public/bot/webhook/message',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ai-settings': typeof AuthenticatedAiSettingsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/vps': typeof AuthenticatedVpsRoute
  '/api/public/meta/webhook': typeof ApiPublicMetaWebhookRoute
  '/api/public/bot/webhook/message': typeof ApiPublicBotWebhookMessageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ai-settings': typeof AuthenticatedAiSettingsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/vps': typeof AuthenticatedVpsRoute
  '/api/public/meta/webhook': typeof ApiPublicMetaWebhookRoute
  '/api/public/bot/webhook/message': typeof ApiPublicBotWebhookMessageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ai-settings': typeof AuthenticatedAiSettingsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/vps': typeof AuthenticatedVpsRoute
  '/api/public/meta/webhook': typeof ApiPublicMetaWebhookRoute
  '/api/public/bot/webhook/message': typeof ApiPublicBotWebhookMessageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ai-settings'
    | '/dashboard'
    | '/vps'
    | '/api/public/meta/webhook'
    | '/api/public/bot/webhook/message'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ai-settings'
    | '/dashboard'
    | '/vps'
    | '/api/public/meta/webhook'
    | '/api/public/bot/webhook/message'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ai-settings'
    | '/_authenticated/dashboard'
    | '/_authenticated/vps'
    | '/api/public/meta/webhook'
    | '/api/public/bot/webhook/message'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicMetaWebhookRoute: typeof ApiPublicMetaWebhookRoute
  ApiPublicBotWebhookMessageRoute: typeof ApiPublicBotWebhookMessageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vps': {
      id: '/_authenticated/vps'
      path: '/vps'
      fullPath: '/vps'
      preLoaderRoute: typeof AuthenticatedVpsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-settings': {
      id: '/_authenticated/ai-settings'
      path: '/ai-settings'
      fullPath: '/ai-settings'
      preLoaderRoute: typeof AuthenticatedAiSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/meta/webhook': {
      id: '/api/public/meta/webhook'
      path: '/api/public/meta/webhook'
      fullPath: '/api/public/meta/webhook'
      preLoaderRoute: typeof ApiPublicMetaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/webhook/message': {
      id: '/api/public/bot/webhook/message'
      path: '/api/public/bot/webhook/message'
      fullPath: '/api/public/bot/webhook/message'
      preLoaderRoute: typeof ApiPublicBotWebhookMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiSettingsRoute: typeof AuthenticatedAiSettingsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedVpsRoute: typeof AuthenticatedVpsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiSettingsRoute: AuthenticatedAiSettingsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedVpsRoute: AuthenticatedVpsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicMetaWebhookRoute: ApiPublicMetaWebhookRoute,
  ApiPublicBotWebhookMessageRoute: ApiPublicBotWebhookMessageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
