/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated/whatsapp'
import { Route as AuthenticatedVpsRouteImport } from './routes/_authenticated/vps'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRiskRouteImport } from './routes/_authenticated/risk'
import { Route as AuthenticatedReplyRulesRouteImport } from './routes/_authenticated/reply-rules'
import { Route as AuthenticatedMessengerRouteImport } from './routes/_authenticated/messenger'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedInstagramRouteImport } from './routes/_authenticated/instagram'
import { Route as AuthenticatedHumanTakeoverRouteImport } from './routes/_authenticated/human-takeover'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConversationsRouteImport } from './routes/_authenticated/conversations'
import { Route as AuthenticatedChannelsRouteImport } from './routes/_authenticated/channels'
import { Route as AuthenticatedBusinessKnowledgeRouteImport } from './routes/_authenticated/business-knowledge'
import { Route as AuthenticatedApiSettingsRouteImport } from './routes/_authenticated/api-settings'
import { Route as AuthenticatedAiSettingsRouteImport } from './routes/_authenticated/ai-settings'
import { Route as ApiPublicMetaWebhookRouteImport } from './routes/api/public/meta.webhook'
import { Route as ApiPublicBotWebhookMessageRouteImport } from './routes/api/public/bot.webhook.message'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVpsRoute = AuthenticatedVpsRouteImport.update({
  id: '/vps',
  path: '/vps',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRiskRoute = AuthenticatedRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReplyRulesRoute = AuthenticatedReplyRulesRouteImport.update({
  id: '/reply-rules',
  path: '/reply-rules',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessengerRoute = AuthenticatedMessengerRouteImport.update({
  id: '/messenger',
  path: '/messenger',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInstagramRoute = AuthenticatedInstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHumanTakeoverRoute =
  AuthenticatedHumanTakeoverRouteImport.update({
    id: '/human-takeover',
    path: '/human-takeover',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConversationsRoute =
  AuthenticatedConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChannelsRoute = AuthenticatedChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBusinessKnowledgeRoute =
  AuthenticatedBusinessKnowledgeRouteImport.update({
    id: '/business-knowledge',
    path: '/business-knowledge',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApiSettingsRoute =
  AuthenticatedApiSettingsRouteImport.update({
    id: '/api-settings',
    path: '/api-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiSettingsRoute = AuthenticatedAiSettingsRouteImport.update({
  id: '/ai-settings',
  path: '/ai-settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicMetaWebhookRoute = ApiPublicMetaWebhookRouteImport.update({
  id: '/api/public/meta/webhook',
  path: '/api/public/meta/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotWebhookMessageRoute =
  ApiPublicBotWebhookMessageRouteImport.update({
    id: '/api/public/bot/webhook/message',
    path: '/api/public/bot/webhook/message',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ai-settings': typeof AuthenticatedAiSettingsRoute
  '/api-settings': typeof AuthenticatedApiSettingsRoute
  '/business-knowledge': typeof AuthenticatedBusinessKnowledgeRoute
  '/channels': typeof AuthenticatedChannelsRoute
  '/conversations': typeof AuthenticatedConversationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/human-takeover': typeof AuthenticatedHumanTakeoverRoute
  '/instagram': typeof AuthenticatedInstagramRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/messenger': typeof AuthenticatedMessengerRoute
  '/reply-rules': typeof AuthenticatedReplyRulesRoute
  '/risk': typeof AuthenticatedRiskRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/vps': typeof AuthenticatedVpsRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/api/public/meta/webhook': typeof ApiPublicMetaWebhookRoute
  '/api/public/bot/webhook/message': typeof ApiPublicBotWebhookMessageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ai-settings': typeof AuthenticatedAiSettingsRoute
  '/api-settings': typeof AuthenticatedApiSettingsRoute
  '/business-knowledge': typeof AuthenticatedBusinessKnowledgeRoute
  '/channels': typeof AuthenticatedChannelsRoute
  '/conversations': typeof AuthenticatedConversationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/human-takeover': typeof AuthenticatedHumanTakeoverRoute
  '/instagram': typeof AuthenticatedInstagramRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/messenger': typeof AuthenticatedMessengerRoute
  '/reply-rules': typeof AuthenticatedReplyRulesRoute
  '/risk': typeof AuthenticatedRiskRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/vps': typeof AuthenticatedVpsRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/api/public/meta/webhook': typeof ApiPublicMetaWebhookRoute
  '/api/public/bot/webhook/message': typeof ApiPublicBotWebhookMessageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ai-settings': typeof AuthenticatedAiSettingsRoute
  '/_authenticated/api-settings': typeof AuthenticatedApiSettingsRoute
  '/_authenticated/business-knowledge': typeof AuthenticatedBusinessKnowledgeRoute
  '/_authenticated/channels': typeof AuthenticatedChannelsRoute
  '/_authenticated/conversations': typeof AuthenticatedConversationsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/human-takeover': typeof AuthenticatedHumanTakeoverRoute
  '/_authenticated/instagram': typeof AuthenticatedInstagramRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/messenger': typeof AuthenticatedMessengerRoute
  '/_authenticated/reply-rules': typeof AuthenticatedReplyRulesRoute
  '/_authenticated/risk': typeof AuthenticatedRiskRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/vps': typeof AuthenticatedVpsRoute
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRoute
  '/api/public/meta/webhook': typeof ApiPublicMetaWebhookRoute
  '/api/public/bot/webhook/message': typeof ApiPublicBotWebhookMessageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ai-settings'
    | '/api-settings'
    | '/business-knowledge'
    | '/channels'
    | '/conversations'
    | '/dashboard'
    | '/human-takeover'
    | '/instagram'
    | '/leads'
    | '/messenger'
    | '/reply-rules'
    | '/risk'
    | '/settings'
    | '/vps'
    | '/whatsapp'
    | '/api/public/meta/webhook'
    | '/api/public/bot/webhook/message'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ai-settings'
    | '/api-settings'
    | '/business-knowledge'
    | '/channels'
    | '/conversations'
    | '/dashboard'
    | '/human-takeover'
    | '/instagram'
    | '/leads'
    | '/messenger'
    | '/reply-rules'
    | '/risk'
    | '/settings'
    | '/vps'
    | '/whatsapp'
    | '/api/public/meta/webhook'
    | '/api/public/bot/webhook/message'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ai-settings'
    | '/_authenticated/api-settings'
    | '/_authenticated/business-knowledge'
    | '/_authenticated/channels'
    | '/_authenticated/conversations'
    | '/_authenticated/dashboard'
    | '/_authenticated/human-takeover'
    | '/_authenticated/instagram'
    | '/_authenticated/leads'
    | '/_authenticated/messenger'
    | '/_authenticated/reply-rules'
    | '/_authenticated/risk'
    | '/_authenticated/settings'
    | '/_authenticated/vps'
    | '/_authenticated/whatsapp'
    | '/api/public/meta/webhook'
    | '/api/public/bot/webhook/message'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicMetaWebhookRoute: typeof ApiPublicMetaWebhookRoute
  ApiPublicBotWebhookMessageRoute: typeof ApiPublicBotWebhookMessageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vps': {
      id: '/_authenticated/vps'
      path: '/vps'
      fullPath: '/vps'
      preLoaderRoute: typeof AuthenticatedVpsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/risk': {
      id: '/_authenticated/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof AuthenticatedRiskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reply-rules': {
      id: '/_authenticated/reply-rules'
      path: '/reply-rules'
      fullPath: '/reply-rules'
      preLoaderRoute: typeof AuthenticatedReplyRulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messenger': {
      id: '/_authenticated/messenger'
      path: '/messenger'
      fullPath: '/messenger'
      preLoaderRoute: typeof AuthenticatedMessengerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instagram': {
      id: '/_authenticated/instagram'
      path: '/instagram'
      fullPath: '/instagram'
      preLoaderRoute: typeof AuthenticatedInstagramRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/human-takeover': {
      id: '/_authenticated/human-takeover'
      path: '/human-takeover'
      fullPath: '/human-takeover'
      preLoaderRoute: typeof AuthenticatedHumanTakeoverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversations': {
      id: '/_authenticated/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AuthenticatedConversationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/channels': {
      id: '/_authenticated/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AuthenticatedChannelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business-knowledge': {
      id: '/_authenticated/business-knowledge'
      path: '/business-knowledge'
      fullPath: '/business-knowledge'
      preLoaderRoute: typeof AuthenticatedBusinessKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/api-settings': {
      id: '/_authenticated/api-settings'
      path: '/api-settings'
      fullPath: '/api-settings'
      preLoaderRoute: typeof AuthenticatedApiSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-settings': {
      id: '/_authenticated/ai-settings'
      path: '/ai-settings'
      fullPath: '/ai-settings'
      preLoaderRoute: typeof AuthenticatedAiSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/meta/webhook': {
      id: '/api/public/meta/webhook'
      path: '/api/public/meta/webhook'
      fullPath: '/api/public/meta/webhook'
      preLoaderRoute: typeof ApiPublicMetaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/webhook/message': {
      id: '/api/public/bot/webhook/message'
      path: '/api/public/bot/webhook/message'
      fullPath: '/api/public/bot/webhook/message'
      preLoaderRoute: typeof ApiPublicBotWebhookMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiSettingsRoute: typeof AuthenticatedAiSettingsRoute
  AuthenticatedApiSettingsRoute: typeof AuthenticatedApiSettingsRoute
  AuthenticatedBusinessKnowledgeRoute: typeof AuthenticatedBusinessKnowledgeRoute
  AuthenticatedChannelsRoute: typeof AuthenticatedChannelsRoute
  AuthenticatedConversationsRoute: typeof AuthenticatedConversationsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHumanTakeoverRoute: typeof AuthenticatedHumanTakeoverRoute
  AuthenticatedInstagramRoute: typeof AuthenticatedInstagramRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedMessengerRoute: typeof AuthenticatedMessengerRoute
  AuthenticatedReplyRulesRoute: typeof AuthenticatedReplyRulesRoute
  AuthenticatedRiskRoute: typeof AuthenticatedRiskRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedVpsRoute: typeof AuthenticatedVpsRoute
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiSettingsRoute: AuthenticatedAiSettingsRoute,
  AuthenticatedApiSettingsRoute: AuthenticatedApiSettingsRoute,
  AuthenticatedBusinessKnowledgeRoute: AuthenticatedBusinessKnowledgeRoute,
  AuthenticatedChannelsRoute: AuthenticatedChannelsRoute,
  AuthenticatedConversationsRoute: AuthenticatedConversationsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHumanTakeoverRoute: AuthenticatedHumanTakeoverRoute,
  AuthenticatedInstagramRoute: AuthenticatedInstagramRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedMessengerRoute: AuthenticatedMessengerRoute,
  AuthenticatedReplyRulesRoute: AuthenticatedReplyRulesRoute,
  AuthenticatedRiskRoute: AuthenticatedRiskRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedVpsRoute: AuthenticatedVpsRoute,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicMetaWebhookRoute: ApiPublicMetaWebhookRoute,
  ApiPublicBotWebhookMessageRoute: ApiPublicBotWebhookMessageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
