/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkflowRouteImport } from './routes/_authenticated/workflow'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated/whatsapp'
import { Route as AuthenticatedVpsRouteImport } from './routes/_authenticated/vps'
import { Route as AuthenticatedSubscriptionsRouteImport } from './routes/_authenticated/subscriptions'
import { Route as AuthenticatedSubscriptionExpiredRouteImport } from './routes/_authenticated/subscription-expired'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRiskRouteImport } from './routes/_authenticated/risk'
import { Route as AuthenticatedRevenueAnalyticsRouteImport } from './routes/_authenticated/revenue-analytics'
import { Route as AuthenticatedRevenueRouteImport } from './routes/_authenticated/revenue'
import { Route as AuthenticatedReplyRulesRouteImport } from './routes/_authenticated/reply-rules'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedMessengerRouteImport } from './routes/_authenticated/messenger'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedLeadFollowupsRouteImport } from './routes/_authenticated/lead-followups'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedInstagramRouteImport } from './routes/_authenticated/instagram'
import { Route as AuthenticatedHumanTakeoverRouteImport } from './routes/_authenticated/human-takeover'
import { Route as AuthenticatedDebugRouteImport } from './routes/_authenticated/debug'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedConversationsRouteImport } from './routes/_authenticated/conversations'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedChannelsRouteImport } from './routes/_authenticated/channels'
import { Route as AuthenticatedBusinessKnowledgeRouteImport } from './routes/_authenticated/business-knowledge'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated/appointments'
import { Route as AuthenticatedApiSettingsRouteImport } from './routes/_authenticated/api-settings'
import { Route as AuthenticatedAiSettingsRouteImport } from './routes/_authenticated/ai-settings'
import { Route as ApiPublicMetaWebhookRouteImport } from './routes/api/public/meta.webhook'
import { Route as ApiPublicHooksLeadFollowupsRouteImport } from './routes/api/public/hooks/lead-followups'
import { Route as ApiPublicHooksInvoiceRemindersRouteImport } from './routes/api/public/hooks/invoice-reminders'
import { Route as ApiPublicHooksExpireSubscriptionsRouteImport } from './routes/api/public/hooks/expire-subscriptions'
import { Route as ApiPublicHooksAppointmentRemindersRouteImport } from './routes/api/public/hooks/appointment-reminders'
import { Route as ApiPublicBotDebugRouteImport } from './routes/api/public/bot.debug'
import { Route as ApiPublicBotWebhookMessageRouteImport } from './routes/api/public/bot.webhook.message'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkflowRoute = AuthenticatedWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVpsRoute = AuthenticatedVpsRouteImport.update({
  id: '/vps',
  path: '/vps',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubscriptionsRoute =
  AuthenticatedSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubscriptionExpiredRoute =
  AuthenticatedSubscriptionExpiredRouteImport.update({
    id: '/subscription-expired',
    path: '/subscription-expired',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRiskRoute = AuthenticatedRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRevenueAnalyticsRoute =
  AuthenticatedRevenueAnalyticsRouteImport.update({
    id: '/revenue-analytics',
    path: '/revenue-analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRevenueRoute = AuthenticatedRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReplyRulesRoute = AuthenticatedReplyRulesRouteImport.update({
  id: '/reply-rules',
  path: '/reply-rules',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessengerRoute = AuthenticatedMessengerRouteImport.update({
  id: '/messenger',
  path: '/messenger',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadFollowupsRoute =
  AuthenticatedLeadFollowupsRouteImport.update({
    id: '/lead-followups',
    path: '/lead-followups',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInstagramRoute = AuthenticatedInstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHumanTakeoverRoute =
  AuthenticatedHumanTakeoverRouteImport.update({
    id: '/human-takeover',
    path: '/human-takeover',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDebugRoute = AuthenticatedDebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConversationsRoute =
  AuthenticatedConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChannelsRoute = AuthenticatedChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBusinessKnowledgeRoute =
  AuthenticatedBusinessKnowledgeRouteImport.update({
    id: '/business-knowledge',
    path: '/business-knowledge',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApiSettingsRoute =
  AuthenticatedApiSettingsRouteImport.update({
    id: '/api-settings',
    path: '/api-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiSettingsRoute = AuthenticatedAiSettingsRouteImport.update({
  id: '/ai-settings',
  path: '/ai-settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicMetaWebhookRoute = ApiPublicMetaWebhookRouteImport.update({
  id: '/api/public/meta/webhook',
  path: '/api/public/meta/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksLeadFollowupsRoute =
  ApiPublicHooksLeadFollowupsRouteImport.update({
    id: '/api/public/hooks/lead-followups',
    path: '/api/public/hooks/lead-followups',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksInvoiceRemindersRoute =
  ApiPublicHooksInvoiceRemindersRouteImport.update({
    id: '/api/public/hooks/invoice-reminders',
    path: '/api/public/hooks/invoice-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksExpireSubscriptionsRoute =
  ApiPublicHooksExpireSubscriptionsRouteImport.update({
    id: '/api/public/hooks/expire-subscriptions',
    path: '/api/public/hooks/expire-subscriptions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAppointmentRemindersRoute =
  ApiPublicHooksAppointmentRemindersRouteImport.update({
    id: '/api/public/hooks/appointment-reminders',
    path: '/api/public/hooks/appointment-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBotDebugRoute = ApiPublicBotDebugRouteImport.update({
  id: '/api/public/bot/debug',
  path: '/api/public/bot/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotWebhookMessageRoute =
  ApiPublicBotWebhookMessageRouteImport.update({
    id: '/api/public/bot/webhook/message',
    path: '/api/public/bot/webhook/message',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ai-settings': typeof AuthenticatedAiSettingsRoute
  '/api-settings': typeof AuthenticatedApiSettingsRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/business-knowledge': typeof AuthenticatedBusinessKnowledgeRoute
  '/channels': typeof AuthenticatedChannelsRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/conversations': typeof AuthenticatedConversationsRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/debug': typeof AuthenticatedDebugRoute
  '/human-takeover': typeof AuthenticatedHumanTakeoverRoute
  '/instagram': typeof AuthenticatedInstagramRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/lead-followups': typeof AuthenticatedLeadFollowupsRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/messenger': typeof AuthenticatedMessengerRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/reply-rules': typeof AuthenticatedReplyRulesRoute
  '/revenue': typeof AuthenticatedRevenueRoute
  '/revenue-analytics': typeof AuthenticatedRevenueAnalyticsRoute
  '/risk': typeof AuthenticatedRiskRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscription-expired': typeof AuthenticatedSubscriptionExpiredRoute
  '/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/vps': typeof AuthenticatedVpsRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/workflow': typeof AuthenticatedWorkflowRoute
  '/api/public/bot/debug': typeof ApiPublicBotDebugRoute
  '/api/public/hooks/appointment-reminders': typeof ApiPublicHooksAppointmentRemindersRoute
  '/api/public/hooks/expire-subscriptions': typeof ApiPublicHooksExpireSubscriptionsRoute
  '/api/public/hooks/invoice-reminders': typeof ApiPublicHooksInvoiceRemindersRoute
  '/api/public/hooks/lead-followups': typeof ApiPublicHooksLeadFollowupsRoute
  '/api/public/meta/webhook': typeof ApiPublicMetaWebhookRoute
  '/api/public/bot/webhook/message': typeof ApiPublicBotWebhookMessageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ai-settings': typeof AuthenticatedAiSettingsRoute
  '/api-settings': typeof AuthenticatedApiSettingsRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/business-knowledge': typeof AuthenticatedBusinessKnowledgeRoute
  '/channels': typeof AuthenticatedChannelsRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/conversations': typeof AuthenticatedConversationsRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/debug': typeof AuthenticatedDebugRoute
  '/human-takeover': typeof AuthenticatedHumanTakeoverRoute
  '/instagram': typeof AuthenticatedInstagramRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/lead-followups': typeof AuthenticatedLeadFollowupsRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/messenger': typeof AuthenticatedMessengerRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/reply-rules': typeof AuthenticatedReplyRulesRoute
  '/revenue': typeof AuthenticatedRevenueRoute
  '/revenue-analytics': typeof AuthenticatedRevenueAnalyticsRoute
  '/risk': typeof AuthenticatedRiskRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscription-expired': typeof AuthenticatedSubscriptionExpiredRoute
  '/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/vps': typeof AuthenticatedVpsRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/workflow': typeof AuthenticatedWorkflowRoute
  '/api/public/bot/debug': typeof ApiPublicBotDebugRoute
  '/api/public/hooks/appointment-reminders': typeof ApiPublicHooksAppointmentRemindersRoute
  '/api/public/hooks/expire-subscriptions': typeof ApiPublicHooksExpireSubscriptionsRoute
  '/api/public/hooks/invoice-reminders': typeof ApiPublicHooksInvoiceRemindersRoute
  '/api/public/hooks/lead-followups': typeof ApiPublicHooksLeadFollowupsRoute
  '/api/public/meta/webhook': typeof ApiPublicMetaWebhookRoute
  '/api/public/bot/webhook/message': typeof ApiPublicBotWebhookMessageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ai-settings': typeof AuthenticatedAiSettingsRoute
  '/_authenticated/api-settings': typeof AuthenticatedApiSettingsRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/business-knowledge': typeof AuthenticatedBusinessKnowledgeRoute
  '/_authenticated/channels': typeof AuthenticatedChannelsRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/conversations': typeof AuthenticatedConversationsRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/debug': typeof AuthenticatedDebugRoute
  '/_authenticated/human-takeover': typeof AuthenticatedHumanTakeoverRoute
  '/_authenticated/instagram': typeof AuthenticatedInstagramRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/lead-followups': typeof AuthenticatedLeadFollowupsRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/messenger': typeof AuthenticatedMessengerRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/reply-rules': typeof AuthenticatedReplyRulesRoute
  '/_authenticated/revenue': typeof AuthenticatedRevenueRoute
  '/_authenticated/revenue-analytics': typeof AuthenticatedRevenueAnalyticsRoute
  '/_authenticated/risk': typeof AuthenticatedRiskRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/subscription-expired': typeof AuthenticatedSubscriptionExpiredRoute
  '/_authenticated/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/_authenticated/vps': typeof AuthenticatedVpsRoute
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRoute
  '/_authenticated/workflow': typeof AuthenticatedWorkflowRoute
  '/api/public/bot/debug': typeof ApiPublicBotDebugRoute
  '/api/public/hooks/appointment-reminders': typeof ApiPublicHooksAppointmentRemindersRoute
  '/api/public/hooks/expire-subscriptions': typeof ApiPublicHooksExpireSubscriptionsRoute
  '/api/public/hooks/invoice-reminders': typeof ApiPublicHooksInvoiceRemindersRoute
  '/api/public/hooks/lead-followups': typeof ApiPublicHooksLeadFollowupsRoute
  '/api/public/meta/webhook': typeof ApiPublicMetaWebhookRoute
  '/api/public/bot/webhook/message': typeof ApiPublicBotWebhookMessageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ai-settings'
    | '/api-settings'
    | '/appointments'
    | '/billing'
    | '/business-knowledge'
    | '/channels'
    | '/clients'
    | '/conversations'
    | '/crm'
    | '/dashboard'
    | '/debug'
    | '/human-takeover'
    | '/instagram'
    | '/invoices'
    | '/lead-followups'
    | '/leads'
    | '/messenger'
    | '/payments'
    | '/reply-rules'
    | '/revenue'
    | '/revenue-analytics'
    | '/risk'
    | '/settings'
    | '/subscription-expired'
    | '/subscriptions'
    | '/vps'
    | '/whatsapp'
    | '/workflow'
    | '/api/public/bot/debug'
    | '/api/public/hooks/appointment-reminders'
    | '/api/public/hooks/expire-subscriptions'
    | '/api/public/hooks/invoice-reminders'
    | '/api/public/hooks/lead-followups'
    | '/api/public/meta/webhook'
    | '/api/public/bot/webhook/message'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ai-settings'
    | '/api-settings'
    | '/appointments'
    | '/billing'
    | '/business-knowledge'
    | '/channels'
    | '/clients'
    | '/conversations'
    | '/crm'
    | '/dashboard'
    | '/debug'
    | '/human-takeover'
    | '/instagram'
    | '/invoices'
    | '/lead-followups'
    | '/leads'
    | '/messenger'
    | '/payments'
    | '/reply-rules'
    | '/revenue'
    | '/revenue-analytics'
    | '/risk'
    | '/settings'
    | '/subscription-expired'
    | '/subscriptions'
    | '/vps'
    | '/whatsapp'
    | '/workflow'
    | '/api/public/bot/debug'
    | '/api/public/hooks/appointment-reminders'
    | '/api/public/hooks/expire-subscriptions'
    | '/api/public/hooks/invoice-reminders'
    | '/api/public/hooks/lead-followups'
    | '/api/public/meta/webhook'
    | '/api/public/bot/webhook/message'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ai-settings'
    | '/_authenticated/api-settings'
    | '/_authenticated/appointments'
    | '/_authenticated/billing'
    | '/_authenticated/business-knowledge'
    | '/_authenticated/channels'
    | '/_authenticated/clients'
    | '/_authenticated/conversations'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/debug'
    | '/_authenticated/human-takeover'
    | '/_authenticated/instagram'
    | '/_authenticated/invoices'
    | '/_authenticated/lead-followups'
    | '/_authenticated/leads'
    | '/_authenticated/messenger'
    | '/_authenticated/payments'
    | '/_authenticated/reply-rules'
    | '/_authenticated/revenue'
    | '/_authenticated/revenue-analytics'
    | '/_authenticated/risk'
    | '/_authenticated/settings'
    | '/_authenticated/subscription-expired'
    | '/_authenticated/subscriptions'
    | '/_authenticated/vps'
    | '/_authenticated/whatsapp'
    | '/_authenticated/workflow'
    | '/api/public/bot/debug'
    | '/api/public/hooks/appointment-reminders'
    | '/api/public/hooks/expire-subscriptions'
    | '/api/public/hooks/invoice-reminders'
    | '/api/public/hooks/lead-followups'
    | '/api/public/meta/webhook'
    | '/api/public/bot/webhook/message'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicBotDebugRoute: typeof ApiPublicBotDebugRoute
  ApiPublicHooksAppointmentRemindersRoute: typeof ApiPublicHooksAppointmentRemindersRoute
  ApiPublicHooksExpireSubscriptionsRoute: typeof ApiPublicHooksExpireSubscriptionsRoute
  ApiPublicHooksInvoiceRemindersRoute: typeof ApiPublicHooksInvoiceRemindersRoute
  ApiPublicHooksLeadFollowupsRoute: typeof ApiPublicHooksLeadFollowupsRoute
  ApiPublicMetaWebhookRoute: typeof ApiPublicMetaWebhookRoute
  ApiPublicBotWebhookMessageRoute: typeof ApiPublicBotWebhookMessageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workflow': {
      id: '/_authenticated/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof AuthenticatedWorkflowRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vps': {
      id: '/_authenticated/vps'
      path: '/vps'
      fullPath: '/vps'
      preLoaderRoute: typeof AuthenticatedVpsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscriptions': {
      id: '/_authenticated/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AuthenticatedSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscription-expired': {
      id: '/_authenticated/subscription-expired'
      path: '/subscription-expired'
      fullPath: '/subscription-expired'
      preLoaderRoute: typeof AuthenticatedSubscriptionExpiredRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/risk': {
      id: '/_authenticated/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof AuthenticatedRiskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/revenue-analytics': {
      id: '/_authenticated/revenue-analytics'
      path: '/revenue-analytics'
      fullPath: '/revenue-analytics'
      preLoaderRoute: typeof AuthenticatedRevenueAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/revenue': {
      id: '/_authenticated/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof AuthenticatedRevenueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reply-rules': {
      id: '/_authenticated/reply-rules'
      path: '/reply-rules'
      fullPath: '/reply-rules'
      preLoaderRoute: typeof AuthenticatedReplyRulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messenger': {
      id: '/_authenticated/messenger'
      path: '/messenger'
      fullPath: '/messenger'
      preLoaderRoute: typeof AuthenticatedMessengerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lead-followups': {
      id: '/_authenticated/lead-followups'
      path: '/lead-followups'
      fullPath: '/lead-followups'
      preLoaderRoute: typeof AuthenticatedLeadFollowupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instagram': {
      id: '/_authenticated/instagram'
      path: '/instagram'
      fullPath: '/instagram'
      preLoaderRoute: typeof AuthenticatedInstagramRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/human-takeover': {
      id: '/_authenticated/human-takeover'
      path: '/human-takeover'
      fullPath: '/human-takeover'
      preLoaderRoute: typeof AuthenticatedHumanTakeoverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/debug': {
      id: '/_authenticated/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof AuthenticatedDebugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversations': {
      id: '/_authenticated/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AuthenticatedConversationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/channels': {
      id: '/_authenticated/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AuthenticatedChannelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business-knowledge': {
      id: '/_authenticated/business-knowledge'
      path: '/business-knowledge'
      fullPath: '/business-knowledge'
      preLoaderRoute: typeof AuthenticatedBusinessKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/api-settings': {
      id: '/_authenticated/api-settings'
      path: '/api-settings'
      fullPath: '/api-settings'
      preLoaderRoute: typeof AuthenticatedApiSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-settings': {
      id: '/_authenticated/ai-settings'
      path: '/ai-settings'
      fullPath: '/ai-settings'
      preLoaderRoute: typeof AuthenticatedAiSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/meta/webhook': {
      id: '/api/public/meta/webhook'
      path: '/api/public/meta/webhook'
      fullPath: '/api/public/meta/webhook'
      preLoaderRoute: typeof ApiPublicMetaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/lead-followups': {
      id: '/api/public/hooks/lead-followups'
      path: '/api/public/hooks/lead-followups'
      fullPath: '/api/public/hooks/lead-followups'
      preLoaderRoute: typeof ApiPublicHooksLeadFollowupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/invoice-reminders': {
      id: '/api/public/hooks/invoice-reminders'
      path: '/api/public/hooks/invoice-reminders'
      fullPath: '/api/public/hooks/invoice-reminders'
      preLoaderRoute: typeof ApiPublicHooksInvoiceRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/expire-subscriptions': {
      id: '/api/public/hooks/expire-subscriptions'
      path: '/api/public/hooks/expire-subscriptions'
      fullPath: '/api/public/hooks/expire-subscriptions'
      preLoaderRoute: typeof ApiPublicHooksExpireSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/appointment-reminders': {
      id: '/api/public/hooks/appointment-reminders'
      path: '/api/public/hooks/appointment-reminders'
      fullPath: '/api/public/hooks/appointment-reminders'
      preLoaderRoute: typeof ApiPublicHooksAppointmentRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/debug': {
      id: '/api/public/bot/debug'
      path: '/api/public/bot/debug'
      fullPath: '/api/public/bot/debug'
      preLoaderRoute: typeof ApiPublicBotDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/webhook/message': {
      id: '/api/public/bot/webhook/message'
      path: '/api/public/bot/webhook/message'
      fullPath: '/api/public/bot/webhook/message'
      preLoaderRoute: typeof ApiPublicBotWebhookMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiSettingsRoute: typeof AuthenticatedAiSettingsRoute
  AuthenticatedApiSettingsRoute: typeof AuthenticatedApiSettingsRoute
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedBusinessKnowledgeRoute: typeof AuthenticatedBusinessKnowledgeRoute
  AuthenticatedChannelsRoute: typeof AuthenticatedChannelsRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedConversationsRoute: typeof AuthenticatedConversationsRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDebugRoute: typeof AuthenticatedDebugRoute
  AuthenticatedHumanTakeoverRoute: typeof AuthenticatedHumanTakeoverRoute
  AuthenticatedInstagramRoute: typeof AuthenticatedInstagramRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedLeadFollowupsRoute: typeof AuthenticatedLeadFollowupsRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedMessengerRoute: typeof AuthenticatedMessengerRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedReplyRulesRoute: typeof AuthenticatedReplyRulesRoute
  AuthenticatedRevenueRoute: typeof AuthenticatedRevenueRoute
  AuthenticatedRevenueAnalyticsRoute: typeof AuthenticatedRevenueAnalyticsRoute
  AuthenticatedRiskRoute: typeof AuthenticatedRiskRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSubscriptionExpiredRoute: typeof AuthenticatedSubscriptionExpiredRoute
  AuthenticatedSubscriptionsRoute: typeof AuthenticatedSubscriptionsRoute
  AuthenticatedVpsRoute: typeof AuthenticatedVpsRoute
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRoute
  AuthenticatedWorkflowRoute: typeof AuthenticatedWorkflowRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiSettingsRoute: AuthenticatedAiSettingsRoute,
  AuthenticatedApiSettingsRoute: AuthenticatedApiSettingsRoute,
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedBusinessKnowledgeRoute: AuthenticatedBusinessKnowledgeRoute,
  AuthenticatedChannelsRoute: AuthenticatedChannelsRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedConversationsRoute: AuthenticatedConversationsRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDebugRoute: AuthenticatedDebugRoute,
  AuthenticatedHumanTakeoverRoute: AuthenticatedHumanTakeoverRoute,
  AuthenticatedInstagramRoute: AuthenticatedInstagramRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedLeadFollowupsRoute: AuthenticatedLeadFollowupsRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedMessengerRoute: AuthenticatedMessengerRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedReplyRulesRoute: AuthenticatedReplyRulesRoute,
  AuthenticatedRevenueRoute: AuthenticatedRevenueRoute,
  AuthenticatedRevenueAnalyticsRoute: AuthenticatedRevenueAnalyticsRoute,
  AuthenticatedRiskRoute: AuthenticatedRiskRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSubscriptionExpiredRoute: AuthenticatedSubscriptionExpiredRoute,
  AuthenticatedSubscriptionsRoute: AuthenticatedSubscriptionsRoute,
  AuthenticatedVpsRoute: AuthenticatedVpsRoute,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRoute,
  AuthenticatedWorkflowRoute: AuthenticatedWorkflowRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicBotDebugRoute: ApiPublicBotDebugRoute,
  ApiPublicHooksAppointmentRemindersRoute:
    ApiPublicHooksAppointmentRemindersRoute,
  ApiPublicHooksExpireSubscriptionsRoute:
    ApiPublicHooksExpireSubscriptionsRoute,
  ApiPublicHooksInvoiceRemindersRoute: ApiPublicHooksInvoiceRemindersRoute,
  ApiPublicHooksLeadFollowupsRoute: ApiPublicHooksLeadFollowupsRoute,
  ApiPublicMetaWebhookRoute: ApiPublicMetaWebhookRoute,
  ApiPublicBotWebhookMessageRoute: ApiPublicBotWebhookMessageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
